# Generated by Django 5.0.4 on 2024-05-01 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
